### Comparando a velocidade de de processamento entre listas e arrays (NumPy)

No exemplo abaixo, uma breve demonstração de tempo para a execução de operações com uma lista x array, considerando a mesma quantidade de elementos para cada um dos objetos.

In [2]:
import numpy as np

# Criando um array em NumPy:
my_arr = np.arange(1000000)

# Criando um list:
my_list = list(range(1000000))

# Realizando um processamento simples entre ambos os objetos, assim como recuperados os tempos e recursos de processamentos para comparação:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 26.9 ms, sys: 5.77 ms, total: 32.6 ms
Wall time: 30.6 ms
CPU times: user 920 ms, sys: 208 ms, total: 1.13 s
Wall time: 1.46 s


### Utilizando o AXIS

Peço que leiam esse artigo pois ele é muito interessante!

O mesmo complementa as explicações dadas em sala de aula sobre o uso do AXIS (eixos) em diferentes situações:

- Entendendo melhor o axis;
- Sua representação em relação ao Array Unidimensinal x Bidimensional;
- Como funciona com funções agregadas (o caso da função 'sum()' que utilizamos em sala de aula).

Além disso, há os desenhos representativos dessas matrizes e como são aplicados o uso dos eixos.


https://www.sharpsightlabs.com/blog/numpy-axes-explained/

### Exclusão de linhas e colunas em um array bidimensional em NumPy:

In [ ]:
# Representação de um Array Bidimensional:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# - Nesse caso, utilizaremos o 'delete' para informar o objeto de dados, o index que desejamos deletar e o eixo.
# - Lembremos que para o eixo ('axis') -> 0 identifica a linha, e 1 a coluna...
# - Abaixo, desejamos deletar o index 2, referente a coluna (por isso, mencionado o axis 1):

np.delete(arr, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [ ]:
# Nesse caso, faremos a exclusão de uma linha (index 1), assim como o axis 0:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])